"""Leakage-safe Group-B / Group-C fitting and cross-fitting orchestration.

This module implements the revised Section 3.3 data flow.  It is intentionally
separate from the downstream neural trainer so that upstream fit scopes can be
audited without inspecting model internals.

Rules implemented here
----------------------
* Blind wells CS9/CS10 are always excluded from upstream fitting.
* The active CP-calibration sample IDs are excluded from the eRF lithology
  corpus wherever ``source_sample_id`` identifies them, and calibration rows
  are never used to fit the Group-C regressors.
* For an outer held-out well, the complete eRF pipeline and both XGBoost
  regressors are refitted without that well.
* For the downstream classifier's own training rows, B and C are generated by
  inner leave-one-well-out cross-fitting: the upstream model producing a row's
  proxies has seen no record from that row's well.
* For the final blind-well model, training-row proxies are cross-fitted over the
  five development wells, while deployment upstream models are fitted on all
  712 non-calibration development rows and then applied to calibration/blind
  rows.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

import numpy as np
import pandas as pd

from src.data.io import LITH_TARGET
from src.features.group_b import ERFLithologyClassifier, GROUP_B_COLUMNS
from src.features.group_c import GROUP_C_COLUMNS, GroupCRegressors


@dataclass(frozen=True)
class UpstreamAudit:
    """Machine-checkable provenance for one upstream fit/predict operation."""

    purpose: str
    target_wells: tuple[str, ...]
    core_fit_wells: tuple[str, ...]
    core_fit_sample_ids: tuple[str, ...]
    lithology_fit_wells: tuple[str, ...]
    lithology_excluded_wells: tuple[str, ...]
    excluded_calibration_source_ids: int


@dataclass(frozen=True)
class ProxyBundle:
    """Aligned B/C features plus fit-scope audit records."""

    group_b: pd.DataFrame
    group_c: pd.DataFrame
    audits: tuple[UpstreamAudit, ...]


@dataclass(frozen=True)
class UpstreamModels:
    """Fitted deployment upstream models plus their audit record.

    This lightweight container is used by the CPU latency benchmark so model
    fitting remains outside the timed inference loop.
    """

    erf: ERFLithologyClassifier
    group_c: GroupCRegressors
    audit: UpstreamAudit


def _normalise_ids(values: Iterable[str]) -> set[str]:
    return {str(v) for v in values if str(v) != ""}


def filter_lithology_corpus(
    corpus: pd.DataFrame,
    *,
    exclude_wells: Iterable[str] = (),
    exclude_source_sample_ids: Iterable[str] = (),
    max_rows_per_class: int | None = None,
) -> pd.DataFrame:
    """Apply only training-side exclusions to the eRF lithology corpus.

    ``max_rows_per_class`` is a synthetic smoke-test acceleration control.  It
    is never enabled by the manuscript/default research driver.
    """
    required = {"well_id", "source_sample_id", LITH_TARGET}
    missing = required - set(corpus.columns)
    if missing:
        raise ValueError(f"lithology corpus missing audit columns: {sorted(missing)}")
    excluded_wells = {str(w) for w in exclude_wells}
    excluded_ids = _normalise_ids(exclude_source_sample_ids)

    mask = ~corpus["well_id"].astype(str).isin(excluded_wells)
    if excluded_ids:
        mask &= ~corpus["source_sample_id"].astype(str).isin(excluded_ids)
    out = corpus.loc[mask].copy()
    if out.empty:
        raise ValueError("No lithology-training rows remain after exclusions.")

    if max_rows_per_class is not None:
        # Synthetic/CI only: deterministic cap after all scientific exclusions.
        out = (
            out.sort_values([LITH_TARGET, "well_id", "depth_m"], kind="stable")
            .groupby(LITH_TARGET, group_keys=False)
            .head(int(max_rows_per_class))
            .reset_index(drop=True)
        )
    return out.reset_index(drop=True)


def _fit_models(
    *,
    core_fit_rows: pd.DataFrame,
    lithology_corpus: pd.DataFrame,
    calibration_sample_ids: Iterable[str],
    exclude_lithology_wells: Iterable[str],
    purpose: str,
    target_wells: Iterable[str],
    erf_n_estimators: int,
    erf_max_depth: int | None,
    erf_random_state: int,
    xgb_random_state: int,
    xgb_overrides: dict | None = None,
    max_lith_rows_per_class: int | None = None,
) -> tuple[ERFLithologyClassifier, GroupCRegressors, UpstreamAudit]:
    if core_fit_rows.empty:
        raise ValueError(f"{purpose}: Group-C fit rows are empty.")
    calibration_ids = _normalise_ids(calibration_sample_ids)
    excluded_wells = tuple(sorted({str(w) for w in exclude_lithology_wells}))
    lith_fit = filter_lithology_corpus(
        lithology_corpus,
        exclude_wells=excluded_wells,
        exclude_source_sample_ids=calibration_ids,
        max_rows_per_class=max_lith_rows_per_class,
    )

    erf = ERFLithologyClassifier(
        n_estimators=int(erf_n_estimators),
        random_state=int(erf_random_state),
        max_depth=erf_max_depth,
    ).fit(lith_fit)
    c_model = GroupCRegressors(
        random_state=int(xgb_random_state), **dict(xgb_overrides or {})
    ).fit(core_fit_rows)

    audit = UpstreamAudit(
        purpose=purpose,
        target_wells=tuple(sorted(set(map(str, target_wells)))),
        core_fit_wells=tuple(sorted(set(core_fit_rows["well_id"].astype(str)))),
        core_fit_sample_ids=tuple(core_fit_rows["sample_id"].astype(str)),
        lithology_fit_wells=tuple(sorted(set(lith_fit["well_id"].astype(str)))),
        lithology_excluded_wells=excluded_wells,
        excluded_calibration_source_ids=len(
            set(lithology_corpus["source_sample_id"].astype(str)) & calibration_ids
        ),
    )
    return erf, c_model, audit



def fit_upstream_models(
    core_fit_rows: pd.DataFrame,
    lithology_corpus: pd.DataFrame,
    *,
    calibration_sample_ids: Iterable[str],
    exclude_lithology_wells: Iterable[str],
    purpose: str = "deployment_upstream",
    target_wells: Iterable[str] = (),
    erf_n_estimators: int = 300,
    erf_max_depth: int | None = None,
    erf_random_state: int = 42,
    xgb_random_state: int = 20260827,
    xgb_overrides: dict | None = None,
    max_lith_rows_per_class: int | None = None,
) -> UpstreamModels:
    """Public wrapper that fits one B/C upstream pipeline without predicting.

    The same scientific exclusions and estimator primitives used by the outer
    and final evaluation paths are reused here.  It is primarily intended for
    the six-stage inference benchmark.
    """
    erf, c_model, audit = _fit_models(
        core_fit_rows=core_fit_rows,
        lithology_corpus=lithology_corpus,
        calibration_sample_ids=calibration_sample_ids,
        exclude_lithology_wells=exclude_lithology_wells,
        purpose=purpose,
        target_wells=target_wells,
        erf_n_estimators=erf_n_estimators,
        erf_max_depth=erf_max_depth,
        erf_random_state=erf_random_state,
        xgb_random_state=xgb_random_state,
        xgb_overrides=xgb_overrides,
        max_lith_rows_per_class=max_lith_rows_per_class,
    )
    return UpstreamModels(erf=erf, group_c=c_model, audit=audit)

def _predict_bundle(
    erf: ERFLithologyClassifier,
    c_model: GroupCRegressors,
    target_rows: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    B = erf.predict_frame(target_rows, index=target_rows.index)
    C = c_model.predict(target_rows).as_frame(index=target_rows.index)
    if list(B.columns) != GROUP_B_COLUMNS or list(C.columns) != GROUP_C_COLUMNS:
        raise AssertionError("Upstream feature column order changed unexpectedly.")
    return B, C


def crossfit_training_proxies(
    training_rows: pd.DataFrame,
    lithology_corpus: pd.DataFrame,
    *,
    calibration_sample_ids: Iterable[str],
    always_exclude_wells: Iterable[str],
    outer_validation_well: str | None = None,
    well_order: Iterable[str] | None = None,
    erf_n_estimators: int = 300,
    erf_max_depth: int | None = None,
    erf_random_state: int = 42,
    xgb_random_state: int = 20260827,
    xgb_overrides: dict | None = None,
    max_lith_rows_per_class: int | None = None,
) -> ProxyBundle:
    """Generate B/C for classifier training rows by inner leave-one-well-out.

    Each target well is predicted by upstream models fitted without *any* row
    from that well.  The returned frames preserve the order/index of
    ``training_rows``.
    """
    if training_rows.index.has_duplicates:
        raise ValueError("training_rows index must be unique for aligned cross-fitting.")
    observed = list(dict.fromkeys(training_rows["well_id"].astype(str).tolist()))
    if well_order is None:
        target_order = observed
    else:
        target_order = [str(w) for w in well_order if str(w) in set(observed)]
    if set(target_order) != set(observed):
        raise ValueError("well_order does not cover all training wells.")

    B_out = pd.DataFrame(index=training_rows.index, columns=GROUP_B_COLUMNS, dtype=float)
    C_out = pd.DataFrame(index=training_rows.index, columns=GROUP_C_COLUMNS, dtype=float)
    audits: list[UpstreamAudit] = []

    base_exclusions = {str(w) for w in always_exclude_wells}
    if outer_validation_well is not None:
        base_exclusions.add(str(outer_validation_well))

    for heldout_well in target_order:
        target_mask = training_rows["well_id"].astype(str) == heldout_well
        target = training_rows.loc[target_mask]
        fit_core = training_rows.loc[~target_mask]
        excluded = set(base_exclusions)
        excluded.add(heldout_well)
        erf, c_model, audit = _fit_models(
            core_fit_rows=fit_core,
            lithology_corpus=lithology_corpus,
            calibration_sample_ids=calibration_sample_ids,
            exclude_lithology_wells=excluded,
            purpose=f"inner_crossfit:{heldout_well}",
            target_wells=[heldout_well],
            erf_n_estimators=erf_n_estimators,
            erf_max_depth=erf_max_depth,
            erf_random_state=erf_random_state,
            xgb_random_state=xgb_random_state,
            xgb_overrides=xgb_overrides,
            max_lith_rows_per_class=max_lith_rows_per_class,
        )
        B, C = _predict_bundle(erf, c_model, target)
        B_out.loc[target.index, :] = B.to_numpy()
        C_out.loc[target.index, :] = C.to_numpy()
        audits.append(audit)

    if B_out.isna().any().any() or C_out.isna().any().any():
        raise AssertionError("Inner cross-fitting left unfilled training proxies.")
    return ProxyBundle(group_b=B_out, group_c=C_out, audits=tuple(audits))


def fit_evaluation_upstream(
    core_fit_rows: pd.DataFrame,
    targets: dict[str, pd.DataFrame],
    lithology_corpus: pd.DataFrame,
    *,
    calibration_sample_ids: Iterable[str],
    always_exclude_wells: Iterable[str],
    evaluation_wells_to_exclude: Iterable[str] = (),
    erf_n_estimators: int = 300,
    erf_max_depth: int | None = None,
    erf_random_state: int = 42,
    xgb_random_state: int = 20260827,
    xgb_overrides: dict | None = None,
    max_lith_rows_per_class: int | None = None,
) -> dict[str, ProxyBundle]:
    """Fit one upstream pipeline and apply it to named evaluation targets.

    This is used per outer fold (fit on that fold's outer-training rows and
    apply to the held-out well + calibration rows) and once for the final model
    (fit on all 712 rows and apply to calibration + blind rows).
    """
    excluded = set(map(str, always_exclude_wells)) | set(
        map(str, evaluation_wells_to_exclude)
    )
    target_wells = sorted(
        {str(w) for df in targets.values() for w in df["well_id"].astype(str).unique()}
    )
    erf, c_model, audit = _fit_models(
        core_fit_rows=core_fit_rows,
        lithology_corpus=lithology_corpus,
        calibration_sample_ids=calibration_sample_ids,
        exclude_lithology_wells=excluded,
        purpose="evaluation_upstream",
        target_wells=target_wells,
        erf_n_estimators=erf_n_estimators,
        erf_max_depth=erf_max_depth,
        erf_random_state=erf_random_state,
        xgb_random_state=xgb_random_state,
        xgb_overrides=xgb_overrides,
        max_lith_rows_per_class=max_lith_rows_per_class,
    )
    out: dict[str, ProxyBundle] = {}
    for name, target in targets.items():
        B, C = _predict_bundle(erf, c_model, target)
        out[name] = ProxyBundle(group_b=B, group_c=C, audits=(audit,))
    return out


def assert_crossfit_audits_no_target_well(audits: Iterable[UpstreamAudit]) -> None:
    """Fail if any inner-crossfit target well appears in an upstream fit scope."""
    for audit in audits:
        if not audit.purpose.startswith("inner_crossfit:"):
            continue
        target = set(audit.target_wells)
        if target & set(audit.core_fit_wells):
            raise AssertionError(f"Group C leakage in {audit.purpose}.")
        if target & set(audit.lithology_fit_wells):
            raise AssertionError(f"Group B leakage in {audit.purpose}.")
